apiVersion: v1
kind: Service
metadata:
  name: jenkins-practice-service
spec:
  type: NodePort # This specifies the service type
  selector:
    app: jenkins-practice-app # Matches the label in the Deployment template
  ports:
    - protocol: TCP
      port: 80          # The service's internal port
      targetPort: 80    # The container's exposed port (from Dockerfile)
      # Kubernetes will automatically assign a NodePort here
